# Site settings
title: Jon Skulski | Enchantobot
email: jon@jonskulski.net
description: > # this means to ignore newlines until "baseurl:"
    Jon Skulski. Software Engineer. Improv. Jokes. Ruby. Python. Testing. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonskulski.net" # the base hostname & protocol for your site
twitter_username: jonskulski
github_username:  jskulski
medium_username: jonskulski
devto_username: jskulski

# Build settings
markdown: kramdown
